services:
  mercado-backend-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        LOCAL_UID: ${LOCAL_UID}
        PULL: true
    container_name: ${CONTAINER_NAME_BACKEND}
    image: ${PROJECT_NAME}_backend:latest
    pull_policy: build
    entrypoint: ["bash", "/usr/local/bin/entrypoint.sh"]
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces/api
    command: sleep infinity
    restart: unless-stopped
    env_file:
      - ../.env.development
    environment:
      - SERVICE_TYPE=backend
      - BINDING=0.0.0.0
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.6
    container_name: ${CONTAINER_NAME_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: