source "https://rubygems.org"

# Core Rails
gem "rails", "~> 8.0.3"
gem "rake", "~> 13.0"

# Database
gem "pg", "~> 1.1"

# cores dentro do outputs do terminal
gem "rainbow", "~> 3.0"
gem "rouge", "~> 4.1"

# Controle de altorização de acessos aos usuarios da aplicação
gem "rolify", "~> 6.0"
gem "pundit", "~> 2.5", ">= 2.5.2"
gem "jwt", "~> 2.8"

# Gem para criação de casos de uso (use cases) na aplicação
gem "u-case", "~> 4.5", ">= 4.5.2"

# user
# gem "devise", "~> 4.9"

# Soft delete
gem "discard", "~> 1.4"

# Server
gem "puma", ">= 5.0"

# Caching and Background Jobs
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Performance
gem "bootsnap", require: false

# Deployment
gem "kamal", require: false
gem "thruster", require: false

# Timezone data
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Uncomment if needed
# gem "jbuilder"
gem "bcrypt", "~> 3.1.7"
# gem "image_processing", "~> 1.2"
# gem "rack-cors"

# gem para acesso administrativo a aplicação
gem "activeadmin", "4.0.0.beta22"

group :development, :test do
  # Debugging
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Security analysis
  gem "brakeman", require: false

  # Load environment variables from .env
  gem "dotenv-rails"

  # Code style
  gem "rubocop-rails-omakase", require: false

  # ER Diagram generation
  gem "rails-erd"

  # Documentação de api e requirido para a gem rswag
  gem "rspec-rails"
  gem "rswag-specs"
  gem "rswag-api"
  gem "rswag-ui"

  # yardocs para documentacao do codigo
  gem "yard"

  # documentação de testes com coverage
  gem "simplecov", require: false
end
